name: debounce_widget
description: A package for debouncing callbacks for certain amount of time.
version: 1.0.0
homepage: https://github.com/dhaval15/debounce_widget

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

